AIRPORTS = [
  { code: "ATL",
    location: "Atlanta" },
  { code: "PEK",
    location: "Beijing" },
  { code: "LAX",
    location: "Los Angeles" },
  { code: "DXB",
    location: "Dubai" },
  { code: "HND",
    location: "Tokyo" },
  { code: "ORD",
    location: "Chicago" },
  { code: "LHR",
    location: "London" },
  { code: "PVG",
    location: "Shanghai" },
  { code: "CDG",
    location: "Paris" },
  { code: "DFW",
    location: "Washington D.C."}
]